### ISSUE TITLE
Could not open library dep_gecode.bundle

### ISSUE THREAD

**Issue by ryzy** [chef/dep-selector#19]
Hi,

I just installed newest Vagrant and newest vagrant-berkshelf (2.0.0.rc3) and I'm having an issues with dep_selector / dep_gecode. Not sure if it's related to Berkshelf or dep-selector itself.

Details:
Chef 11.10.0 (solo)

```
$ vagrant -v
Vagrant 1.5.2

$ vagrant plugin list
vagrant-berkshelf (2.0.0.rc3)
  - Version Constraint: 2.0.0.rc3
vagrant-login (1.0.1, system)
vagrant-share (1.0.1, system)
```

Vagrant fails even for 'vagrant status' command:

``` bash
[ryzy@ryzy-mbp : ~]$ vagrant status
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

Could not open library '/Users/ryzy/.vagrant.d/gems/gems/dep_selector-1.0.0.rc.2/lib/dep_gecode.bundle': dlopen(/Users/ryzy/.vagrant.d/gems/gems/dep_selector-1.0.0.rc.2/lib/dep_gecode.bundle, 5): Symbol not found: __ZN6Gecode16ValBranchOptions3defE
  Referenced from: /Users/ryzy/.vagrant.d/gems/gems/dep_selector-1.0.0.rc.2/lib/dep_gecode.bundle
  Expected in: flat namespace
 in /Users/ryzy/.vagrant.d/gems/gems/dep_selector-1.0.0.rc.2/lib/dep_gecode.bundle
```

There's more details here - and there's more people reporting this just recently:
https://github.com/berkshelf/vagrant-berkshelf/issues/173

Many thanks for looking at it.
M.

**Comment by cloneluke** [comment]
I've had some issues in this area, did the following
gem uninstall dep_selector
gem uninstall dep-selector-libgecode

and then re-installed
